name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: tests
          python-version: 3.11
      - name: Install dependencies
        run: |
          conda install freecad:freecad
          python -m pip install --upgrade pip
          pip install -e .
          pip install -e .[dev]
      - name: Run tests
        run: |
          python -m pytest -v
