name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: freecad
          create-args: >-
            python=3.11
            freecad=0.21.2
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -e .[dev]
          python -m pytest -v
