name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge
          channel-priority: strict
          mamba-version: "*"
          activate-environment: tests
          auto-update-conda: false
          python-version: 3.11
          use-only-tar-bz2: true
        run: |
          mamba install -y freecad=0.21.2
          python -m pip install --upgrade pip
          pip install -e .
          pip install -e .[dev]
      - name: Run tests
        run: |
          python -m pytest -v
